# Generated by Django 3.2.4 on 2021-06-26 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_account', models.IntegerField(auto_created=True, blank=True, null=True, unique=True)),
                ('login', models.CharField(max_length=36, unique=True)),
                ('password', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('build', models.CharField(blank=True, max_length=36, null=True)),
                ('apartment', models.CharField(blank=True, max_length=36, null=True)),
                ('deposit', models.IntegerField(default=0.0)),
                ('registration', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
            },
        ),
    ]
